name: ishaan
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: 6.1.4
  animations: ^2.0.8
  cupertino_icons: ^1.0.8
  model_viewer_plus: ^1.9.3
  gif_view: ^1.0.2
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/body_outline.png
    - assets/brain.png
    - assets/eyes.png
    - assets/heart.png
    - assets/legs.png
    - assets/lungs.png
    - assets/muscle.png
    - assets/stomach.png
    - assets/Blueberries.png
    - assets/tomatoes.png
    - assets/spinach.png
    - assets/beetroot.png
    - assets/oranges.png
    - assets/carrots.png
    - assets/papaya.png
    - assets/cabbage.png
    - assets/apples.png
    - assets/bananas.png
    - assets/vitamink.png
    - assets/gif/brain_fact.gif
    - assets/vitaminc.png
    - assets/gif/heart_fact.gif
    - assets/broccoli.png
    - assets/vitamine.png
    - assets/gif/lung_fact.gif
    - assets/vitamina.png
    - assets/gif/eye_fact.gif
    - assets/vitaminb.png
    - assets/gif/stomach_fact.gif
    - assets/kale.png
    - assets/vitamind.png
    - assets/gif/muscle_fact.gif
    - assets/models/brain.glb
    - assets/models/heart.glb
    - assets/models/eye.glb
    - assets/models/lungs.glb
    - assets/models/stomach.glb
    - assets/models/muscle.glb
    - assets/models/leg.glb
    - assets/pineapple.png
    - assets/sweet potato.png
    - assets/vitaminb12.png
    - assets/gif/leg_fact.gif
    - assets/models/banana.glb
    - assets/pomegranate.png
    - assets/models/pomegranate.glb
    - assets/models/blueberry.glb
    - assets/avocado.png
    - assets/models/avocado.glb
    - assets/models/beetroot.glb
    - assets/models/broccoli.glb
    - assets/models/tomato.glb
    - assets/models/vitamin_c.glb
    - assets/models/potassium.glb
    - assets/potassium.png
    - assets/models/apple.glb
    - assets/models/spinach.glb
    - assets/models/redonion.glb
    - assets/redonion.png
    - assets/cucumber.png
    - assets/models/cucumber.glb
    - assets/models/vitamin_b.glb
    - assets/models/vitamin_e.glb
    - assets/models/vitamin_k.glb


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/Poppins-Regular.ttf
    - family: ComicNeue
      fonts:
        - asset: assets/ComicNeue-Bold.ttf
