name: ishaan
description: A new Flutter project.

publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  animations: ^2.0.8
  cupertino_icons: ^1.0.8
  model_viewer_plus: ^1.9.3
  gif_view: ^1.0.2
  carousel_slider: ^5.0.0
  flutter_tts: ^4.2.2
  google_generative_ai: ^0.4.7
  speech_to_text: ^7.0.0
  string_similarity: ^2.1.1
  rename: ^3.1.0
  shared_preferences: ^2.5.3
  video_player: ^2.9.5
  google_sign_in: ^6.1.6
  flutter_secure_storage: ^9.2.4
  firebase_core: ^2.27.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.15.10
  ionicons: ^0.2.2
  lottie: ^3.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/brain.png
    - assets/eyes.png
    - assets/heart.png
    - assets/legs.png
    - assets/lungs.png
    - assets/muscle.png
    - assets/stomach.png
    - assets/Blueberries.png
    - assets/tomatoes.png
    - assets/spinach.png
    - assets/beetroot.png
    - assets/oranges.png
    - assets/carrots.png
    - assets/papaya.png
    - assets/cabbage.png
    - assets/apples.png
    - assets/bananas.png
    - assets/vitamink.png
    - assets/gif/brain_fact.gif
    - assets/gif/brain_fact2.png
    - assets/vitaminc.png
    - assets/gif/heart_fact.gif
    - assets/broccoli.png
    - assets/vitamine.png
    - assets/gif/lung_fact.gif
    - assets/vitamina.png
    - assets/gif/eye_fact.gif
    - assets/vitaminb.png
    - assets/gif/stomach_fact.gif
    - assets/kale.png
    - assets/vitamind.png
    - assets/gif/muscle_fact.gif
    - assets/models/brain.glb
    - assets/models/heart.glb
    - assets/models/eye.glb
    - assets/models/lungs.glb
    - assets/models/stomach.glb
    - assets/models/muscle.glb
    - assets/models/leg.glb
    - assets/pineapple.png
    - assets/sweet potato.png
    - assets/vitaminb12.png
    - assets/gif/leg_fact.gif
    - assets/models/banana.glb
    - assets/pomegranate.png
    - assets/models/pomegranate.glb
    - assets/models/blueberry.glb
    - assets/avocado.png
    - assets/models/avocado.glb
    - assets/models/beetroot.glb
    - assets/models/broccoli.glb
    - assets/models/tomato.glb
    - assets/models/vitamin_c.glb
    - assets/models/potassium.glb
    - assets/potassium.png
    - assets/models/apple.glb
    - assets/models/spinach.glb
    - assets/models/redonion.glb
    - assets/redonion.png
    - assets/cucumber.png
    - assets/models/cucumber.glb
    - assets/models/vitamin_b.glb
    - assets/models/vitamin_e.glb
    - assets/models/vitamin_k.glb
    - assets/mango.png
    - assets/models/mango.glb
    - assets/models/blackberries.glb
    - assets/blackberry.png
    - assets/kiwi.png
    - assets/models/carrot.glb
    - assets/models/red_bell_pepper.glb
    - assets/redbellpepper.png
    - assets/models/vitamin_a.glb
    - assets/lutein.png
    - assets/models/lutein.glb
    - assets/models/pineapple.glb
    - assets/models/cauliflower.glb
    - assets/cauliflower.png
    - assets/models/cauliflower.glb
    - assets/models/garlic.glb
    - assets/garlic.png
    - assets/models/vitamin_d.glb
    - assets/models/papaya.glb
    - assets/models/sweet_potato.glb
    - assets/models/watermelon.glb
    - assets/watermelon.png
    - assets/grape.png
    - assets/models/grape.glb
    - assets/models/onion.glb
    - assets/onion.png
    - assets/models/mushroom.glb
    - assets/mushroom.png
    - assets/models/tangerine.glb
    - assets/tangerine.png
    - assets/FishTestImage.png
    - assets/mascot/CocoTalking.gif
    - assets/mascot/Coco.png
    - assets/alzheimerdisease.png
    - assets/headache.png
    - assets/salmon.png
    - assets/models/peach.glb
    - assets/peach.png
    - assets/chickenbreast.png
    - assets/welcome page.png
    - assets/videos/body_screen_help.mp4
    - assets/google logo.png
    - assets/mascot/Melonzo.png
    - assets/mascot/MelonzoTalking.gif
    - assets/models/male_body.glb
    - assets/models/female_body.glb
    - assets/animations/light/loading.json
    - assets/animations/dark/loading.json
    - assets/animations/dark/welcome.json
    - assets/animations/light/welcome.json
    - assets/animations/dark/chatbg.json
    - assets/animations/light/chatbg.json
    - assets/beefliver.png
    - assets/animations/light/click.json
    - assets/animations/dark/click.json
    - assets/animations/no-results.json
    - assets/turkeybreast.png
    - assets/duckmeat.png
    - assets/yellowbellpepper.png
    - assets/cottage cheese.png
    - assets/milk.png


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/Poppins-Regular.ttf
    - family: ComicNeue
      fonts:
        - asset: assets/ComicNeue-Bold.ttf
